---
# Wolters Kluwer Backstage compliant catalog info
# See https://backstage.io/docs/features/software-catalog/descriptor-format
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: php-sepa-xml
  description: "SEPA file generator in PHP"
  annotations:
    wolterskluwer.io/bit-id: '041800002496'
spec:
  type: library
  lifecycle: production
  owner: Glenn.Van-Den-Broeck@wolterskluwer.com
links:
  - url: "https://sonarqube.cloud-dev.wolterskluwer.eu/dashboard?id=clearfacts%\
    3Aphp-sepa-xml"
    type: SAST
    title: SonarQube
  - url: "https://wolterskluwer.app.blackduck.com/api/projects/3d5da9ec-8af1-4c\
    4d-b949-4d74942760dd"
    type: SCA
    title: Black Duck
  - url: "https://test4tools.cchaxcess.com/CxWebClient/ProjectStateSummary.aspx\
    ?projectid=17859"
    type: SAST
    title: Checkmarx
